import { Interface } from "ethers";

/** Contracts the dashboard talks to. */
export const FRONTEND_CONTRACTS = [
  "IntentCaptureModule",
  "TriggerMechanism",
  "ExecutionAgent",
  "LexiconHolder",
  "SunsetProtocol",
  "IPToken",
];

/** Where the generated module lives, relative to the repository root. */
export const FRONTEND_ABIS_PATH = "frontend/src/contracts/abis.js";

/**
 * Builds human-readable ABIs (with parameter and struct field names, so the
 * dashboard can read results as `intent.corpusHash`) from compiled artifacts.
 *
 * @param {{readArtifact: (name: string) => Promise<{abi: object[]}>}} artifacts
 *   Hardhat's artifacts manager.
 * @returns {Promise<Record<string, string[]>>} ABIs keyed by contract name.
 */
export async function buildFrontendAbis(artifacts) {
  const abis = {};
  for (const name of FRONTEND_CONTRACTS) {
    const { abi } = await artifacts.readArtifact(name);
    abis[name] = new Interface(abi).format(false);
  }
  return abis;
}

/** Renders the generated ABIs as the frontend module source. */
export function renderAbisModule(abis) {
  return [
    "// Auto-generated by `npm run export-abis` from the compiled contracts.",
    "// Do not edit by hand: test/FrontendAbis.test.js fails if this file drifts",
    "// from the contracts.",
    "",
    `export const CONTRACT_ABIS = ${JSON.stringify(abis, null, 2)}`,
    "",
  ].join("\n");
}
